name: al_takamul_alteqani_test
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # state management
  flutter_bloc: ^8.1.3
  # local storage
  shared_preferences: ^2.2.1
  dio_http_cache:
    git: https://github.com/abdalrhmn1000/Dio-Http-Cache
  # helper packages
  intl: ^0.18.0
  collection: ^1.17.0
  dartz: ^0.10.1

  # for API integration and other helpers
  logger: ^2.0.1
  dio: ^5.3.2
  curl_logger_dio_interceptor: ^1.0.0
  # routing
  go_router: ^9.0.1
  # for responsive
  flutter_screenutil: ^5.8.4
  #for DI and build runner generator
  get_it: ^7.6.0
  injectable: 2.2.0
  retrofit: ^4.0.1
  # for using annotation in json serializable
  json_annotation: ^4.8.1

  #for UI
  cached_network_image: ^3.3.0
  timeago: ^3.4.0

  #for lunch url
  url_launcher: ^6.1.14

  al_takamul_alteqani_test_plugin:
    git: https://github.com/abdalrhmn1000/Al-Takamul-Alteqani-Test-Plugin
  #for internet
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.0
  build_runner: ^2.4.6
  flutter_gen: ^5.3.1
  injectable_generator: ^2.1.6
  retrofit_generator: ^7.0.8


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
